# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-01-31 13:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='pub_date',
            field=models.DateTimeField(auto_now_add=True, default='pub_date'),
            preserve_default=False,
        ),
    ]
