# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-02-03 14:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0002_auto_20200203_0922'),
    ]

    operations = [
        migrations.AlterField(
            model_name='description',
            name='image_description',
            field=models.CharField(max_length=130),
        ),
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
